# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'english-japanese-translater' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for english-japanese-translater
  use_frameworks!
pod 'SwiftyJSON'
pod 'Alamofire', '~> 3.4'
  # Pods for opashi
pod 'RealmSwift'
end
